name: my first workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: who are you
          run: whoami
        - name: where are you
          run: pwd
        - name: os parameters
          run: uname -a
        - name: List files
          run: ls -lrt
        - name: checkout
          uses: actions/checkout@v4
        - name: checkout README.md file
          run: cat README.md  
          
    