name: variable-secrets
on: push
env:
  APP_NAME: action-level-variable
jobs:
    step-level-variables:
        env:
         APP_NAME: job-level-variable
        runs-on: ubuntu-latest
        steps:
        - name: step-level-variables
          env:
            APP_NAME: step-level-variable
          run: echo "name of the application is ${{env.APP_NAME}}"

    action-level-variable:
        runs-on: ubuntu-latest
        steps:
        - name: action-level-variable
          run: echo "name of the application is ${{env.APP_NAME}}"