name: variable-secrets
on: push
jobs:
    env:
      APP_NAME: essentials
    step-level-variables:
        runs-on: ubuntu-latest
        steps:
        - name: step-level-variables
          env:
            APP_NAME: analyzer
          run: echo "name of the application is $APP_NAME"