name: variable-secrets
on: push
env:
  APP_NAME: essentials
jobs:
    step-level-variables:
        runs-on: ubuntu-latest
        steps:
        - name: step-level-variables
          env:
            APP_NAME: analyzer
          run: echo "name of the application is ${{env.APP_NAME}}